#init:
#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/install-git-2.11.1.ps1?v=2'))

test_script:
- git config --global core.longpaths true
- md C:\Users\appveyor\AppData\Local\Temp\1\npm-2900-8b1a0fe2\git-cache-397d6243\2430cdb3ef7fc9e1a93d9ed0f7cb8321679d7963
- git clone https://github.com/FeodorFitsner/git-long-paths.git C:\Users\appveyor\AppData\Local\Temp\1\npm-2900-8b1a0fe2\git-cache-397d6243\2430cdb3ef7fc9e1a93d9ed0f7cb8321679d7963

build: off
